name: Extract Firmware Images

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            unace unrar zip unzip p7zip-full p7zip-rar sharutils rar \
            uudeview mpack arj cabextract rename liblzma-dev python3-pip \
            brotli lz4 build-essential python3-dev
          pip3 install backports.lzma protobuf pycryptodome

      - name: Clone Firmware_extractor
        run: |
          git clone --recurse-submodules https://github.com/AndroidDumps/dumpyara

      - name: Download firmware
        run: |
          cd dumpyara
          wget https://dl.google.com/dl/android/aosp/lynx-bp1a.250505.005.b1-factory-45a1393f.zip -O firmware.zip

      - name: Extract images
        run: |
          cd dumpyara
          chmod +x setup.sh dumpyara.sh
          bash setup.sh
          bash dumpyara.sh firmware.zip
          ls firmware

      - name: Upload init_boot.img
        uses: actions/upload-artifact@v4
        with:
          name: init_boot-img
          path: firmware/init_boot.img
